/*
 * @Author: qinjinyuan
 * @Date: 2025-03-06 11:10:49
 * @LastEditTime: 2025-03-06 18:00:04
 * @FilePath: \my-app-one\src\app\layout.tsx
 */
import './globals.css';

import type { Metadata } from 'next';
import {
  Abhaya_Libre,
  Geist,
  Geist_Mono,
} from 'next/font/google';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin']
})

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin']
})
const abc = Abhaya_Libre({
  weight: '400'
})

export const metadata: Metadata = {
  title: 'HOME',
  description: 'Generated by create next app'
}

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <div className="flex">{children}</div>
        <div className={abc.className}>1231312313123</div>
      </body>
    </html>
  )
}
